#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("codeidx_ap_vld", 1, hls_in, 17, "ap_vld", "in_vld", 1),
	Port_Property("c_0", 8, hls_out, 0, "ap_vld", "out_data", 1),
	Port_Property("c_0_ap_vld", 1, hls_out, 0, "ap_vld", "out_vld", 1),
	Port_Property("c_1", 8, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("c_1_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("c_2", 8, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("c_2_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("c_3", 8, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("c_3_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("d_0", 8, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("d_1", 8, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("d_2", 8, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("d_3", 8, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("d_4", 8, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("d_5", 8, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("d_6", 8, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("d_7", 8, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("d_8", 8, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("d_9", 8, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("d_10", 8, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("d_11", 8, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("survival_pattern", 16, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("codeidx", 8, hls_in, 17, "ap_vld", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "rs_erasure";
