// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_rs_erasure (
unsigned char c[4],
unsigned char d[12],
unsigned short survival_pattern,
unsigned char codeidx);
